export const OBTENER_NOTIFICACIONES = 'OBTENER_NOTIFICACIONES';
export const AUMENTAR_CANTIDAD = 'AUMENTAR_CANTIDAD';
export const REINICIAR_CANTIDAD = 'REINICIAR_CANTIDAD';
export const REINICIAR_CONTENIDO = 'REINICIAR_CONTENIDO';
export const GUARDAR_TOKEN_FIREBASE = 'GUARDAR_TOKEN_FIREBASE';
export const GUARDAR_MENSAJES = 'GUARDAR_MENSAJES';
export const GUARDAR_CHATROOM = 'GUARDAR_CHATROOM';
export const NUEVO_MENSAJE = 'NUEVO_MENSAJE';