export const OBTENER_NOTIFICACIONES = 'OBTENER_NOTIFICACIONES';
export const AUMENTAR_CANTIDAD = 'AUMENTAR_CANTIDAD';
export const REINICIAR_CANTIDAD = 'REINICIAR_CANTIDAD';
export const REINICIAR_CONTENIDO = 'REINICIAR_CONTENIDO';